<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The file catalogue, and the lead image on articles and pages.
 *
 * RESTRICT on media.uploaded_by_id, so an account owning files cannot be
 * deleted; SET NULL on both featured_image_id columns, so deleting a file
 * leaves the content intact without one.
 *
 * The unique index on media.filename is the backstop under the generated name:
 * a collision is not a thing that happens with sixteen random bytes, and if it
 * somehow does, this catches it rather than silently overwriting.
 */
final class Version20260816214731 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create media and add featured images';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploaded_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2CA10C3C0BE965 ON media (filename)');
        $this->addSql('CREATE INDEX IDX_6A2CA10CA2B28FE8 ON media (uploaded_by_id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article ADD featured_image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E663569D950 FOREIGN KEY (featured_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_23A0E663569D950 ON article (featured_image_id)');
        $this->addSql('ALTER TABLE page ADD featured_image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB6203569D950 FOREIGN KEY (featured_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_140AB6203569D950 ON page (featured_image_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CA2B28FE8');
        $this->addSql('DROP TABLE media');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E663569D950');
        $this->addSql('DROP INDEX IDX_23A0E663569D950');
        $this->addSql('ALTER TABLE article DROP featured_image_id');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB6203569D950');
        $this->addSql('DROP INDEX IDX_140AB6203569D950');
        $this->addSql('ALTER TABLE page DROP featured_image_id');
    }
}
