<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The table behind `Forgotten your password?`.
 *
 * `token_hash` and not `token`: a reset token in a database is a working link,
 * so only its SHA-256 hash is stored and the value that opens the link exists
 * only in the email that was sent.
 *
 * `ON DELETE CASCADE` on the account: an outstanding request for a deleted
 * account is a link to nothing, and keeping it would leave rows nobody can
 * reach.
 */
final class Version20260817094827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create password_reset_request';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_reset_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, used BOOLEAN NOT NULL, token_hash VARCHAR(64) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5D0A95A9B6B5FBA ON password_reset_request (account_id)');
        $this->addSql('ALTER TABLE password_reset_request ADD CONSTRAINT FK_C5D0A95A9B6B5FBA FOREIGN KEY (account_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_reset_request DROP CONSTRAINT FK_C5D0A95A9B6B5FBA');
        $this->addSql('DROP TABLE password_reset_request');
    }
}
