<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The record of who did what.
 *
 * `actor_id` is nullable with `ON DELETE SET NULL`, and `actor_label` holds
 * the address as text. Together they are what makes an entry outlive the account
 * that made it: a log that goes blank when somebody leaves is a log about
 * nothing, and the moment anybody most wants to read it is the moment after
 * something disappeared.
 *
 * The subject is text for the same reason. A reference to a row that has been
 * deleted is not information.
 */
final class Version20260817101015 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create audit_entry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(40) NOT NULL, subject VARCHAR(255) NOT NULL, actor_label VARCHAR(180) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C6AF98710DAF24A ON audit_entry (actor_id)');
        $this->addSql('CREATE INDEX idx_audit_entry_occurred_at ON audit_entry (occurred_at)');
        $this->addSql('ALTER TABLE audit_entry ADD CONSTRAINT FK_2C6AF98710DAF24A FOREIGN KEY (actor_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE audit_entry DROP CONSTRAINT FK_2C6AF98710DAF24A');
        $this->addSql('DROP TABLE audit_entry');
    }
}
