<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Articles and pages: the same lifecycle columns in both tables, because they
 * come from one mapped superclass.
 *
 * The unique index on slug is per table, which is what lets an article and a
 * page share an address. ON DELETE RESTRICT on article.author_id is what makes
 * "an account owning content cannot be deleted" hold even for a caller that
 * never heard of UserDeleter.
 */
final class Version20260816211106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create article and page';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, excerpt TEXT DEFAULT NULL, content TEXT NOT NULL, status VARCHAR(16) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66989D9B62 ON article (slug)');
        $this->addSql('CREATE INDEX IDX_23A0E66F675F31B ON article (author_id)');
        $this->addSql('CREATE INDEX idx_article_listing ON article (status, published_at)');
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, excerpt TEXT DEFAULT NULL, content TEXT NOT NULL, status VARCHAR(16) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_140AB620989D9B62 ON page (slug)');
        $this->addSql('CREATE INDEX idx_page_listing ON page (status, published_at)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66F675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66F675F31B');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE page');
    }
}
