<?php

declare(strict_types=1);

namespace App\DataFixtures;

use function abs;
use function crc32;

use GdImage;

use function imagecolorallocate;
use function imagecreatetruecolor;
use function imagedestroy;
use function imagefill;
use function imagefilledrectangle;
use function imagegif;
use function imagejpeg;
use function imagepng;
use function imagewebp;
use function ob_get_clean;
use function ob_start;

use RuntimeException;

/**
 * Draws a development placeholder image.
 *
 * **Drawn rather than shipped.** A repository that carries binary assets to make
 * its fixtures look nice is a repository that grows, and the bytes are never
 * reviewed by anybody. Everything here is generated by GD from a seed, so the
 * repository stays text and the same seed always produces the same picture.
 *
 * It replaces a one-by-one grey pixel. That was defensible while nothing resized
 * anything — a browser stretches it to whatever the layout asks for — but feature
 * 012 made the site request a thumbnail, a medium and a large, and a single pixel
 * scaled to sixteen hundred is not a picture of anything. A development site that
 * looks broken teaches people to ignore it looking broken.
 *
 * The picture is deliberately not a photograph: two flat bands of colour, chosen
 * from the seed. Nobody should mistake development data for real content.
 */
final readonly class PlaceholderImage
{
    /**
     * Large enough that every derived size is a genuine reduction, small enough
     * that six of them cost nothing to generate on every fixture load.
     */
    private const int WIDTH = 1200;

    private const int HEIGHT = 800;

    /**
     * @param string $seed anything stable — the stored filename is ideal, since
     *                     it makes each catalogued file a different picture and the same one
     *                     every time
     */
    public function draw(string $seed, string $mimeType): string
    {
        $image = imagecreatetruecolor(self::WIDTH, self::HEIGHT);

        if (false === $image) {
            throw new RuntimeException('GD could not create an image.');
        }

        try {
            $this->paint($image, $seed);

            return $this->encode($image, $mimeType);
        } finally {
            imagedestroy($image);
        }
    }

    private function paint(GdImage $image, string $seed): void
    {
        // A stable number from the seed, so that a given file always looks the
        // same and two files rarely look alike.
        $hue = abs(crc32($seed));

        $background = imagecolorallocate($image, 40 + $hue % 60, 60 + $hue % 90, 90 + $hue % 120);
        $band = imagecolorallocate($image, 200 - $hue % 70, 190 - $hue % 60, 170 - $hue % 50);

        if (false === $background || false === $band) {
            throw new RuntimeException('GD could not allocate a colour.');
        }

        imagefill($image, 0, 0, $background);

        // One band across the lower third: enough shape that a resized copy
        // visibly differs from a solid rectangle, which is what makes a broken
        // thumbnail obvious at a glance.
        imagefilledrectangle($image, 0, (int) (self::HEIGHT * 0.62), self::WIDTH, self::HEIGHT, $band);
    }

    private function encode(GdImage $image, string $mimeType): string
    {
        ob_start();

        $written = match ($mimeType) {
            'image/png' => imagepng($image, null, 6),
            'image/gif' => imagegif($image),
            'image/webp' => imagewebp($image, null, 82),
            // JPEG for anything else that reaches here, which in practice is
            // only image/jpeg — a type with no image is handled before this.
            default => imagejpeg($image, null, 82),
        };

        $bytes = (string) ob_get_clean();

        if (false === $written || '' === $bytes) {
            throw new RuntimeException('GD could not encode the placeholder.');
        }

        return $bytes;
    }
}
